### ISSUE TITLE
Clean .gitignore file

### ISSUE THREAD

**Issue by windwhisper99** [Amilelne/MyToDo#2]
For platform like MacOS. there are really "awkward" .DS_Store hidden files, storing directory cache.
After you realized and put it into `.gitignore` file but didn't affect remote repo. Use:
```bash
git rm --cache **/.DS_Store
git commit <commit message>
``` 
To remove all .DS_Store files in your repository from remote and local.

For best practice. Just copy & paste existing `.gitignore` file for Node JS from the Internet (github gist). To make sure you don't missed any file to case painful after

**Comment by Amilelne** [comment]
got it, thx~
